name: Travel Safely - CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Verificación simple
      run: echo "Todo listo. Proyecto HTML/CSS/JS sin dependencias"
